### PR TITLE
Server init

### PR DESCRIPTION
**Pull request by wdurhamh**
So a classic work flow is for the programmer to create a new branch locally, make changes, commit those changes to the branch, push the branch, and create a pull request. It's easter than it sounds.
1.)CREATE NEW BRANCH - "git checkout -b <new branch name>
2.)MAKE YOUR CHANGES
3.)COMMIT (just like normal)
4.)PUSH NEW BRANCH TO ORIGIN - "git push -u origin <new branch name>"
5.)CREATE PULL REQUEST - git on github and look at the repo in the browser, There should be a green button saying 'Create pull request'
6.)The other guy then go over your changes to make sure everyone's on the same page. If he likes it, he can merge the branch

Once you've pushed and the new branched has been merged, switch back to the 'master branch' local
- "git checkout master"

This may not be necessary, but it's good practice.

### CODE REVIEW

**Comment by thebeeph** [comment]
I guess I still have questions about node on git. I went ahead and committed + pushed your changes, but how does git display stuff on my localhost? I guess it’s because the repo is cloned locally on my machine, so the node server listens for an event on port 3000? Is that right?

I’m not sure where I need to be when I run npm start. Been looking for where the git repo is stored, but I can’t find information that corresponds to how my folders look in Terminal. Any advice for how to find that storage location so I can run the thing?

Thanks, as always, for taking my ignorance gracefully.

**Comment by wdurhamh** [comment]
To the see the changes locally, pull the changes to the local repo
>cd <path to repo directory>
>git pull

That updates your local repo.
To run,
>cd <path to repo directory>
>npm start

If you don't know where the local repo is, you could try searching your
system for a .git file. If worst comes to worst, just clone it again. If
you can come by at 6:30 ish we could figure it out together.

2016-03-28 12:24 GMT-06:00 Nephi Henry <notifications@github.com>:

> I guess I still have questions about node on git. I went ahead and
> committed + pushed your changes, but how does git display stuff on my
> localhost? I guess it’s because the repo is cloned locally on my machine,
> so the node server listens for an event on port 3000? Is that right?
>
> I’m not sure where I need to be when I run npm start. Been looking for
> where the git repo is stored, but I can’t find information that corresponds
> to how my folders look in Terminal. Any advice for how to find that storage
> location so I can run the thing?
>
> Thanks, as always, for taking my ignorance gracefully.
>
> > On Mar 24, 2016, at 4:50 PM, winston.hurst@familysearch.org <

**Comment by thebeeph** [comment]
Cool, that’s what I was trying to do. Glad I was on the right track. Just not sure why I can’t find my repo directory.

**Comment by thebeeph** [comment]
Ok, finally got it. Thanks again.

**Pull request merged**
